account/urls.py
from django.urls import path, include

from . import views, views_registration

app_name = 'account'
urlpatterns = [
    path('profile/', include([
        path('', views.view, name='view'),
        path('view/<str:username>/', views.view_user, name='view_user'),
        path('edit/', views.edit, name='edit')
    ])),
    path('account/', include([
        path('', views.preferences, name='preferences'),
        path('payment/', views.preferences_payment, name='payment'),
        path('payment_history/', views.preferences_payment_history, name='payment_history'),
        path('close/', views.close, name='close')
    ])),
    # Registration views
    path('register/', include([
        path('', views_registration.register, name='register'),
        path('join/<int:group_id>', views_registration.register_and_join_group, name='register_and_join'),
        path('done/', views_registration.register_success, name='registration_success'),
        path('activate/<str:activation_key>', views_registration.activate, name='registration_activate'),
    ])),

    # Usage example: $.post( "/memo/about/2/", "lorem ipsum dolor sit amet");
    path('memo/about/<str:about_user_id>/', views.create_or_update_memo, name='memo')
]

bokaru/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = \
    [
        path('', include('web.urls')),
        path('', include('account.urls')),
        path('event/', include('event.urls')),
        path('chat/', include('chat.urls')),
        path('admin/', admin.site.urls),
        path('script/activate_events/', views.activate_events),
        path('script/process_payments/', views.process_payments),
        # Authentication views
        path('', include('django.contrib.auth.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'event'
urlpatterns = [
    path('create/', login_required(views.CreateEventWizard.as_view()), name='create'),
    path('<int:event_id>/', views.view, name='view'),
    path('join/<int:group_id>/', views.join, name='join'),
    path('join_confirmation/', views.join_confirmation, name='join_confirmation'),
    path('leave/<int:event_id>/', views.leave, name='leave'),
    path('leave_confirmation/', views.leave_confirmation, name='leave_confirmation')
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

web/urls.py
from django.urls import path

from . import views

app_name = 'web'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('search/<str:place_name>/', views.search_by_place, name='search_by_place'),
    path('my_events/', views.my_events, name='my_events'),
    path('my_matches/', views.my_matches, name='my_matches'),
    # ============
    # Static pages
    # ============
    path('about_us/', views.about_us, name='about_us'),
    path('browser_support/', views.browser_support, name='browser_support'),
    path('community_guidelines/', views.community_guidelines, name='community_guidelines'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('how_it_works/', views.how_it_works, name='how_it_works'),
    path('pricing/', views.pricing, name='pricing'),
    path('privacy_statement/', views.privacy_statement, name='privacy_statement'),
    path('refund_policy/', views.refund_policy, name='refund_policy'),
    path('safety_tips/', views.safety_tips, name='safety_tips'),
    path('terms_of_service/', views.terms_of_service, name='terms_of_service')
]

event/views.py
import base64
import io
import logging
from datetime import datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.gis.geos import Point
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse, get_object_or_404
from django.utils import timezone
from django.utils.dateparse import parse_time
from formtools.wizard.views import SessionWizardView
from stripe import CardError

from bokaru.email import send_email
from money.billing_logic import get_product_by_event_size, get_price_by_user, pay_for_event
from money.model_transaction import Transaction
from money.models import UserPaymentInfo
from money.payment_service import CardDeclinedException
from .forms import CreateEventStep1, CreateEventStep2, CreateEventStep3, CreateEventStep4, CreateEventStep5, \
    CreateEventStep6
from .models import Event, EventGroup, EventParticipant

# Get an instance of a logger
LOGGER = logging.getLogger(__name__)


# Return a value from a tuple list by key
def get_value(tuples, key):
    dictionary = dict(tuples)
    if key in dictionary:
        return dictionary[key]

    return ''


def view(request, event_id):
    # Fetch the event by ID
    selected_event = get_object_or_404(Event, pk=event_id)

    display_price = float(get_price_by_user(request.user, selected_event)) / 100
    can_leave = False
    can_join = False

    # Get group info
    event_groups = list(selected_event.eventgroup_set.all())
    group1 = event_groups[0]
    group2 = None
    if selected_event.numGroups == 2:
        group2 = event_groups[1]

    # First group info
    group1_participants = group1.get_registered_participants_accounts()
    group1_filled_count = group1_participants.count()
    group1_filled_percentage = round(float(group1_filled_count) / selected_event.maxParticipantsInGroup * 100)
    group1_can_join = False

    # Second group info
    group2_participants = []
    group2_filled_percentage = 0
    group2_filled_count = 0
    group2_can_join = False
    if selected_event.numGroups == 2:
        group2_participants = group2.get_registered_participants_accounts()
        group2_filled_count = group2_participants.count()
        group2_filled_percentage = round(float(group2_filled_count) / selected_event.maxParticipantsInGroup * 100)

    # Check if user can join each group and leave event
    if request.user.is_authenticated and request.user is not None:
        try:
            can_leave = selected_event.can_user_leave(request.user)
        except Exception:
            can_leave = False

        try:
            group1_can_join = group1.can_user_register(request.user)
            can_join = True
        except Exception:
            group1_can_join = False

        if selected_event.numGroups == 2:
            try:
                group2_can_join = group2.can_user_register(request.user)
                can_join = True
            except Exception:
                group2_can_join = False
    else:
        can_join = True
        group1_can_join = True
        group2_can_join = True

    context = {
        'event': selected_event,
        'group1': group1,
        'group2': group2,
        'group1_filled_percentage': group1_filled_percentage,
        'group2_filled_percentage': group2_filled_percentage,
        'group1_filled_count': group1_filled_count,
        'group2_filled_count': group2_filled_count,
        'group1_participants': group1_participants,
        'group2_participants': group2_participants,
        'group1_can_join': group1_can_join,
        'group2_can_join': group2_can_join,
        'display_price': display_price,
        'can_join': can_join,
        'can_leave': can_leave
    }

    return render(request, 'event/view.html', context)


class CreateEventWizard(SessionWizardView):
    FORMS = [
        ('step1', CreateEventStep1),
        ('step2', CreateEventStep2),
        ('step3', CreateEventStep3),
        ('step4', CreateEventStep4),
        ('step5', CreateEventStep5),
        ('step6', CreateEventStep6)
    ]

    TEMPLATES = {
        'step1': 'event/create/step1.html',
        'step2': 'event/create/step2.html',
        'step3': 'event/create/step3.html',
        'step4': 'event/create/step4.html',
        'step5': 'event/create/step5.html',
        'step6': 'event/create/step6.html'
    }

    form_list = FORMS

    def showStep4a(self):
        cleaned_data = self.get_cleaned_data_for_step('step3') or {}
        if cleaned_data.get('numGroups') == 1:
            return True
        else:
            return False

    def showStep4b(self):
        cleaned_data = self.get_cleaned_data_for_step('step3') or {}
        if cleaned_data.get('numGroups') == 2:
            return True
        else:
            return False

    def get_template_names(self):
        return [CreateEventWizard.TEMPLATES[self.steps.current]]

    def get_context_data(self, form, **kwargs):
        context = super(CreateEventWizard, self).get_context_data(form=form, **kwargs)
        if self.steps.current == 'step6':
            all_data = self.get_all_cleaned_data()

            # Calculate start datetime
            start_date = all_data.get('date')
            start_time = all_data.get('time')
            start_time = parse_time(start_time)
            start_date_time = datetime.combine(start_date, start_time)
            start_date_time = timezone.get_current_timezone().localize(start_date_time)
            all_data.update({'start_date_time': start_date_time})

            # Convert certain values into display format
            all_data.update({'displayType': get_value(Event.TYPES, int(all_data.get('type')))})

            all_data.update({'displayNumDates': int(all_data.get('eventSize')) / 2})
            all_data.update({'displayDuration': int(all_data.get('eventSize')) * 3})

            if all_data.get('sexualIdentity2') == '':
                all_data.update({'displayNumParticipantsPerGroup': int(all_data.get('eventSize')) / 2 + 1})

                display_sexual_identity1 = get_value(EventGroup.IDENTITY_CHOICES, all_data.get('sexualIdentity'))
                if all_data.get('sexualIdentity') == 'other':
                    display_sexual_identity1 = all_data.get('sexualIdentityOther')
                all_data.update({'displaySexualIdentity1': display_sexual_identity1})
            else:
                all_data.update({'displayNumParticipantsPerGroup': int(all_data.get('eventSize')) / 2})

                display_sexual_identity1 = get_value(EventGroup.IDENTITY_CHOICES, all_data.get('sexualIdentity1'))
                if all_data.get('sexualIdentity1') == 'other':
                    display_sexual_identity1 = all_data.get('sexualIdentityOther1')
                all_data.update({'displaySexualIdentity1': display_sexual_identity1})
                display_sexual_identity2 = get_value(EventGroup.IDENTITY_CHOICES, all_data.get('sexualIdentity2'))
                if all_data.get('sexualIdentity2') == 'other':
                    display_sexual_identity2 = all_data.get('sexualIdentityOther2')
                all_data.update({'displaySexualIdentity2': display_sexual_identity2})
            context.update({'all_data': all_data})
        return context

    def done(self, form_list, **kwargs):
        # Save the event
        all_data = self.get_all_cleaned_data()

        # Calculate start datetime
        start_date = all_data.get('date')
        start_time = all_data.get('time')
        start_time = parse_time(start_time)
        start_date_time = datetime.combine(start_date, start_time)
        start_date_time = timezone.get_current_timezone().localize(start_date_time)

        # Get number of groups and participants
        if all_data.get('sexualIdentity2') == '':
            num_participants = int(all_data.get('eventSize')) / 2 + 1
            num_groups = 1
        else:
            num_participants = int(all_data.get('eventSize')) / 2
            num_groups = 2

        # Create geo point
        lat = all_data.get('cityLat')
        lng = all_data.get('cityLng')
        point = Point(x=0, y=0, srid=4326)

        if lat and lng:
            point.x = lng
            point.y = lat

        # Get appropriate product
        product = get_product_by_event_size(int(all_data.get('eventSize')))

        event = Event(
            creator=self.request.user,
            name=all_data.get('name'),
            type=all_data.get('type'),
            size=all_data.get('eventSize'),
            startDateTime=start_date_time,
            locationName=all_data.get('locationName'),
            locationCoordinates=point,
            divisionCode=all_data.get('division'),
            countryCode=all_data.get('country'),
            description=all_data.get('description'),
            numGroups=num_groups,
            maxParticipantsInGroup=num_participants,
            product=product
        )
        event.save()

        # Add photo
        if all_data.get('image_data') and len(all_data.get('image_data')) > 0:
            img_format, img_data = all_data.get('image_data').split(';base64,')
            byte_stream = io.BytesIO(base64.b64decode(img_data))
            event.add_photo(byte_stream, 800)

        # Save event groups
        if num_groups == 1:
            group = EventGroup(
                event=event,
                sexualIdentity=all_data.get('sexualIdentity1'),
                sexualIdentityOther=all_data.get('sexualIdentityOther1'),
                ageMin=all_data.get('ageMin1'),
                ageMax=all_data.get('ageMax1')
            )
            group.save()
        else:
            group1 = EventGroup(
                event=event,
                sexualIdentity=all_data.get('sexualIdentity1'),
                sexualIdentityOther=all_data.get('sexualIdentityOther1'),
                ageMin=all_data.get('ageMin1'),
                ageMax=all_data.get('ageMax1')
            )

event/templates/event/event_tag_large.html
{% load staticfiles %}
{% load event_tags %}

<article class="g-rounded-4 g-py-20 event g-pos-rel {% if event.promoted %}promoted{% endif %}">
    <a href="{% url 'event:view' event_id=event.id %}" class="overlay"></a>
    <div class="row g-ml-0">
        <div class="col-md-4 g-mb-0--md">
            <div class="g-pos-rel u-shadow-v2 g-brd-around g-brd-white g-brd-2">
                <!-- Event image -->
                <figure>
                    {% if event.photo is None or event.photo.name == '' %}
                    <img class="img-fluid w-100" src="{% static 'web/images/event_default_image.jpg' %}" alt="Default event picture"/>
                    {% else %}
                    <img class="img-fluid w-100" src="{{ event.photoMedium.url }}" alt="Event picture"/>
                    {% endif %}
                </figure>

                <!-- Event type -->
                <div class="g-pos-abs g-top-0 g-left-0 d-inline-block">
                    <div class="d-flex justify-content-between w-100 g-max-width-145 g-bg-black g-color-white g-font-size-13 g-font-weight-700 text-uppercase">
                    <span class="g-px-5 g-py-2">
                        {% if event.type == 1 %}
                        <i class="fa fa-heart g-mr-3"></i>
                        {% elif event.type == 2 %}
                        <i class="fa fa-heart-o g-mr-3"></i>
                        {% elif event.type == 3 %}
                        <i class="fa fa-glass g-mr-3"></i>
                        {% elif event.type == 4 %}
                        <i class="fa fa-handshake-o g-mr-3"></i>
                        {% elif event.type == 5 %}
                        <i class="fa fa-diamond g-mr-3"></i>
                        {% endif %}
                    </span>
                        <span class="g-bg-primary g-font-weight-700 g-px-5 g-py-3 text-uppercase">
                        {{ event.displayType }}
                    </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <!-- Event -->
            <header class="g-mb-15 g-mr-15">
                <h1 class="g-font-weight-300 g-font-size-30 g-line-height-1">
                    {{ event.name|truncatechars:40 }}
                    {% event_labels event %}
                </h1>
                <h2 class="g-font-weight-300 g-color-primary g-font-size-20 mb-0">{{ event.startDateTime|date:'l, N d, Y @ P' }}</h2>
                <h3 class="g-color-dark g-font-weight-400 g-font-size-20 mb-0">{{ event.locationName }}</h3>
            </header>

            <!-- Event Description -->
            <p class="lead">{{ event.description | linebreaks | truncatewords:15 }}</p>

            <!-- Event Info -->
            <div class="g-overflow-hidden g-mb-15 g-mr-15">
                <ul class="list-inline g-brd-top g-brd-bottom g-brd-gray-light-v3 g-font-size-12 text-center g-mx-minus-25">
                    <li class="list-inline-item g-width-30x g-pa-12-5-7 mx-0 g-my-5 over-overlay"
                        data-toggle="tooltip" title="Number of people you meet">
                        <i class="align-middle icon-people g-color-gray-dark-v4 g-font-size-18 g-mr-5"></i>
                        {{ event.numPeopleYouMeet }}
                    </li>
                    <li class="list-inline-item g-width-30x g-brd-left g-brd-gray-light-v3 g-pa-12-5-7 mx-0 g-my-5 over-overlay"
                        data-toggle="tooltip" title="Total even duration">
                        <i class="align-middle icon-clock g-color-gray-dark-v4 g-font-size-18 g-mr-5"></i>
                        {{ event.duration }} min.
                    </li>
                    <li class="list-inline-item g-width-30x g-brd-left g-brd-gray-light-v3 g-pa-12-5-7 mx-0 g-my-5 over-overlay"
                        data-toggle="tooltip" title="Filled percentage">
                        <i class="align-middle icon-speedometer g-color-gray-dark-v4 g-font-size-18 g-mr-5"></i>
                        {{ event.filledPercentage | floatformat:"0" }}%
                    </li>
                </ul>
            </div>

            <!-- Groups -->
            <div class="row">
                <div class="col-6 col-md-2">
                    <div class="js-pie g-color-black"
                         data-circles-value="{{ group1_filled_percentage }}"
                         data-circles-max-value="100"
                         data-circles-bg-color="#222"
                         data-circles-fg-color="#e74c3c"
                         data-circles-radius="35"
                         data-circles-stroke-width="4"
                         data-circles-font-size="14"
                         data-circles-font-weight="700"
                         data-circles-additional-text="%"
                         data-circles-duration="2000"
                         data-circles-scroll-animate="false">
                    </div>
                </div>
                <div class="col-6 col-md-4">
                    <span class="g-color-black g-font-weight-700">{{ group1.displaySexualIdentity }}</span>
                    <em class="d-block g-font-style-normal">Ages: {{ group1.ageMin }} &mdash; {{ group1.ageMax }}</em>
                    {% if group1_can_join %}
                    {% if is_authenticated %}
                    <a href="{% url 'event:join' group_id=group1.id %}"
                       class="btn u-btn-primary u-btn-content g-font-weight-600 g-letter-spacing-0_5 text-uppercase g-brd-2 rounded-0 over-overlay">
                        <i class="fa fa-heart pull-left"></i>
                        <span class="float-right text-left">
                            Join group
                        </span>
                    </a>
                    {% else %}
                    <a href="{% url 'account:register_and_join' group_id=group1.id %}"
                       class="btn u-btn-primary u-btn-content g-font-weight-600 g-letter-spacing-0_5 text-uppercase g-brd-2 rounded-0 over-overlay">
                        <i class="fa fa-heart pull-left"></i>
                        <span class="float-right text-left">
                            Join group
                        </span>
                    </a>
                    {% endif %}
                    {% endif %}
                </div>
                {% if group2 %}
                <div class="col-6 col-md-2">
                    <div class="js-pie g-color-black"
                         data-circles-value="{{ group2_filled_percentage }}"
                         data-circles-max-value="100"
                         data-circles-bg-color="#222"
                         data-circles-fg-color="#e74c3c"
                         data-circles-radius="35"
                         data-circles-stroke-width="4"
                         data-circles-font-size="14"
                         data-circles-font-weight="700"
                         data-circles-additional-text="%"
                         data-circles-duration="2000"
                         data-circles-scroll-animate="false">
                    </div>
                </div>
                <div class="col-6 col-md-4">
                    <span class="g-color-black g-font-weight-700">{{ group2.displaySexualIdentity }}</span>
                    <em class="d-block g-font-style-normal">Ages: {{ group2.ageMin }} &mdash; {{ group2.ageMax }}</em>
                    {% if group2_can_join %}
                    {% if is_authenticated %}
                    <a href="{% url 'event:join' group_id=group2.id %}"
                       class="btn u-btn-primary u-btn-content g-font-weight-600 g-letter-spacing-0_5 text-uppercase g-brd-2 rounded-0 over-overlay">
                        <i class="fa fa-heart pull-left"></i>
                        <span class="float-right text-left">
                            Join group
                        </span>
                    </a>
                    {% else %}
                    <a href="{% url 'account:register_and_join' group_id=group2.id %}"
                       class="btn u-btn-primary u-btn-content g-font-weight-600 g-letter-spacing-0_5 text-uppercase g-brd-2 rounded-0 over-overlay">
                        <i class="fa fa-heart pull-left"></i>
                        <span class="float-right text-left">
                            Join group
                        </span>
                    </a>
                    {% endif %}
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</article>

event/templates/event/event_tag_small.html
{% load staticfiles %}
{% load event_tags %}

<article class="g-bg-white text-center rounded g-mb-5 event g-pos-rel {% if event.promoted %}promoted{% endif %}">
    <a href="{% url 'event:view' event_id=event.id %}" class="overlay"></a>
    <!-- Event Header -->
    <header class="g-py-10 g-height-100">
        <h1 class="h5 g-mb-5">
            {{ event.name|truncatechars:30 }}
            {% event_labels_small event %}
        </h1>
        <div class="d-block g-color-black g-font-weight-600 g-letter-spacing-1 text-uppercase g-mb-0">
            <h2 class="g-font-weight-300 g-font-size-10 mb-0">{{ event.startDateTime|date:'l, N d, Y @ P' }}</h2>
            <h3 class="g-color-dark g-font-weight-400 g-font-size-10 mb-0">{{ event.locationName }}</h3>
        </div>
    </header>

    <div class="g-pos-rel">
        <!-- Event Image -->
        <figure>
            {% if event.photo is None or event.photo.name == '' %}
            <img class="img-fluid w-100" src="{% static 'web/images/event_default_image.jpg' %}" alt="Default event picture"/>
            {% else %}
            <img class="img-fluid w-100" src="{{ event.photoMedium.url }}" alt="Event picture"/>
            {% endif %}
        </figure>

        <!-- Event type -->
        <div class="g-pos-abs g-top-0 g-left-0 d-inline-block">
            <div class="d-flex justify-content-between w-100 g-max-width-145 g-bg-black g-color-white g-font-size-13 g-font-weight-700 text-uppercase">
                <span class="g-px-5 g-py-2">
                    {% if event.type == 1 %}
                    <i class="fa fa-heart g-mr-3"></i>
                    {% elif event.type == 2 %}
                    <i class="fa fa-heart-o g-mr-3"></i>
                    {% elif event.type == 3 %}
                    <i class="fa fa-glass g-mr-3"></i>
                    {% elif event.type == 4 %}
                    <i class="fa fa-handshake-o g-mr-3"></i>
                    {% elif event.type == 5 %}
                    <i class="fa fa-diamond g-mr-3"></i>
                    {% endif %}
                </span>
                <span class="g-bg-primary g-font-weight-700 g-px-5 g-py-3 text-uppercase">
                    {{ event.displayType }}
                </span>
            </div>
        </div>
    </div>

    <footer class="w-100">
        <!-- Event Info -->
        <div class="g-overflow-hidden">
            <ul class="list-inline g-brd-top g-brd-bottom g-brd-gray-light-v3 g-font-size-12 text-center g-mx-minus-25 g-mb-0">
                <li class="list-inline-item g-width-30x g-pa-12-5-7 mx-0 g-my-5 over-overlay"
                    data-toggle="tooltip" title="Number of people you meet">
                    <i class="align-middle icon-people g-color-gray-dark-v4 g-font-size-18 g-mr-5"></i>
                    {{ event.numPeopleYouMeet }}
                </li>
                <li class="list-inline-item g-width-30x g-brd-left g-brd-gray-light-v3 g-pa-12-5-7 mx-0 g-my-5 over-overlay"
                    data-toggle="tooltip" title="Total even duration">
                    <i class="align-middle icon-clock g-color-gray-dark-v4 g-font-size-18 g-mr-5"></i>
                    {{ event.duration }} min.
                </li>
                <li class="list-inline-item g-width-30x g-brd-left g-brd-gray-light-v3 g-pa-12-5-7 mx-0 g-my-5 over-overlay"
                    data-toggle="tooltip" title="Filled percentage">
                    <i class="align-middle icon-speedometer g-color-gray-dark-v4 g-font-size-18 g-mr-5"></i>
                    {{ event.filledPercentage | floatformat:"0" }}%
                </li>
            </ul>
        </div>
    </footer>
</article>

event/templates/event/join_confirmation.html
{% extends 'web/base_nav.html' %}

{% load staticfiles %}

{% block title %}Bokaru | Joined event {{ event.name }}{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-6 g-offset-md-3 g-my-100 text-center u-zigzag-top u-zigzag-bottom">
                <!-- Event Info -->
                <div class="u-heading-v1-1 g-bg-secondary g-brd-primary g-my-50">
                    <h1 class="u-heading-v1__title">You have successfully joined the event!</h1>
                </div>
                <h1 class="g-color-dark g-font-weight-300 g-font-size-45 g-line-height-1 mb-4">
                    <a href="{% url 'event:view' event_id=event.id %}">{{ event.name }}</a>
                </h1>
                <h2 class="g-font-weight-300 g-font-size-30 mb-0">{{ event.startDateTime|date:'l, N d, Y @ P' }}</h2>
                <h3 class="g-color-primary g-font-weight-400 g-font-size-30 mb-0">{{ event.locationName }}</h3>

                <!-- Group Info -->
                <div class="u-heading-v1-1 g-bg-secondary g-brd-primary g-my-30">
                    <h1 class="u-heading-v1__title">Group Info</h1>
                </div>
                <h1 class="g-color-primary g-font-weight-600">
                    {{ group.displaySexualIdentity }}
                </h1>
                <h2 class="g-mb-100">
                    Ages: <span class="u-label u-label--lg g-rounded-3 g-bg-primary g-mr-10 g-mb-15">{{ group.ageMin }} &mdash; {{ group.ageMax }}</span>
                </h2>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>
    gtag('event', 'event_confirm', {
        'event_category': 'engagement',
        'event_label': '{{event.name}}',
        'eventValue': '{{ expected_revenue }}'
    });
</script>
{% endblock %}

event/templates/event/leave.html
{% extends 'web/base_nav.html' %}

{% load staticfiles %}

{% block title %}Bokaru | Leave event {{ event.name }}{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-6 g-offset-md-3 g-my-100 text-center u-zigzag-top u-zigzag-bottom">
                <!-- Event Info -->
                <div class="u-heading-v1-1 g-bg-secondary g-brd-primary g-my-50">
                    <h1 class="u-heading-v1__title">Are you sure you want to leave this event?</h1>
                </div>
                <h1 class="g-color-dark g-font-weight-300 g-font-size-45 g-line-height-1 mb-4">
                    <a href="{% url 'event:view' event_id=event.id %}">{{ event.name }}</a>
                </h1>
                <h2 class="g-font-weight-300 g-font-size-30 mb-0">{{ event.startDateTime|date:'l, N d, Y @ P' }}</h2>
                <h3 class="g-color-primary g-font-weight-400 g-font-size-30 mb-0">{{ event.locationName }}</h3>

                <form method="post">
                    {% csrf_token %}
                    <button class="btn btn-lg btn-block u-btn-primary g-mt-20 rounded-0">
                        Yes, I'm sure!
                    </button>
                    <a href="{% url 'event:view' event_id=event.id %}" class="btn btn-lg btn-block u-btn-black g-mt-20 g-mb-50 rounded-0">
                        Nope, I changed my mind!
                    </a>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>
    gtag('event', 'event_leave', {
        'event_category': 'engagement',
        'event_label': '{{ event.name }}',
    });
</script>
{% endblock %}

event/templates/event/leave_confirmation.html
{% extends 'web/base_nav.html' %}

{% load staticfiles %}

{% block title %}Bokaru | Left event {{ event.name }}{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-6 g-offset-md-3 g-my-100 text-center u-zigzag-top u-zigzag-bottom">
                <!-- Event Info -->
                <div class="u-heading-v1-1 g-bg-secondary g-brd-primary g-my-50">
                    <h1 class="u-heading-v1__title">Sorry to see you go!</h1>
                </div>

                <h4>Why not join another event?</h4>
                <a href="{% url 'web:search' %}" class="btn btn-lg btn-block u-btn-black g-my-50 rounded-0">
                    Search events
                </a>

                {% if refund > 0 %}
                <h1 class="g-color-dark g-font-weight-300 g-font-size-45 g-line-height-1 g-mb-20">
                    We refunded the credit used for this event:
                </h1>
                <h2 class="g-font-weight-300 g-font-size-30 g-mb-50 g-color-primary">
                    CAD ${{refund|floatformat:"2"}}
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>
    gtag('event', 'event_leave_confirm', {
        'event_category': 'engagement',
        'event_label': '{{ event.name }}',
    });
</script>
{% endblock %}