bokaru/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = \
    [
        path('', include('web.urls')),
        path('', include('account.urls')),
        path('event/', include('event.urls')),
        path('chat/', include('chat.urls')),
        path('admin/', admin.site.urls),
        path('script/activate_events/', views.activate_events),
        path('script/process_payments/', views.process_payments),
        # Authentication views
        path('', include('django.contrib.auth.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.live_event, name='live_event'),
    path('test/', views.network_test, name='network_test'),
    # ex: /chat/pick/target_user/123/event/456/response/1/
    # Responses are: 1 - Yes, 0 - No and 2 - Maybe
    path('pick/target_user/<int:target_user_id>/event/<int:event_id>/response/<int:response>/',
         views.create_pick, name='create_pick'),
    # path('test/<int:user1>/<int:user2>/', views.live_event_test)
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

web/urls.py
from django.urls import path

from . import views

app_name = 'web'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('search/<str:place_name>/', views.search_by_place, name='search_by_place'),
    path('my_events/', views.my_events, name='my_events'),
    path('my_matches/', views.my_matches, name='my_matches'),
    # ============
    # Static pages
    # ============
    path('about_us/', views.about_us, name='about_us'),
    path('browser_support/', views.browser_support, name='browser_support'),
    path('community_guidelines/', views.community_guidelines, name='community_guidelines'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('how_it_works/', views.how_it_works, name='how_it_works'),
    path('pricing/', views.pricing, name='pricing'),
    path('privacy_statement/', views.privacy_statement, name='privacy_statement'),
    path('refund_policy/', views.refund_policy, name='refund_policy'),
    path('safety_tips/', views.safety_tips, name='safety_tips'),
    path('terms_of_service/', views.terms_of_service, name='terms_of_service')
]

chat/models.py
import logging

from django.conf import settings
from django.db import models

from event.models import Event
from account.models import Account, Memo

logger = logging.getLogger(__name__)


class ConversationManager(models.Manager):
    def mark_token_requested(self, conversation_id):
        conversation = self.get(pk=conversation_id)
        conversation.tokenRequested = True
        conversation.save()


class Conversation(models.Model):
    BREAK = 'break'

    event = models.ForeignKey(Event, on_delete=models.PROTECT)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user', on_delete=models.PROTECT)
    order = models.PositiveSmallIntegerField()
    interlocutorUser = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='interlocutor', blank=True, null=True,
                                         on_delete=models.SET_NULL)
    interlocutorAccount = models.ForeignKey(Account, blank=True, null=True, on_delete=models.SET_NULL)
    interlocutorMemo = models.ForeignKey(Memo, blank=True, null=True, on_delete=models.SET_NULL)
    sessionID = models.CharField(max_length=200, blank=True, null=True)
    tokenRequested = models.BooleanField(default=False)

    # Automatic timestamps
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # Custom manager
    objects = ConversationManager()

    def __str__(self):
        interlocutor = Conversation.BREAK
        if self.interlocutorUser is not None:
            interlocutor = self.interlocutorUser.username

        return 'Event: ' + str(self.event.id) + '[' + str(self.order) + '] | user ' \
               + str(self.user) + ' talks to ' + interlocutor

chat/views.py
import logging

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from opentok import OpenTok, MediaModes

from event.models import Event, Pick
from money.model_transaction import Transaction
from .models import Conversation
from .utils import get_current_date, get_user_dates

api_key = settings.TOKBOX_KEY
api_secret = settings.TOKBOX_SECRET

# Get an instance of a logger
LOGGER = logging.getLogger(__name__)


@login_required
def live_event(request):
    # Get the current event
    event = Event.objects.get_current(request.user)

    if event is None:
        next_event = Event.objects.get_next(request.user)

        return render(request, 'chat/no_live.html', {'next_event': next_event})

    if event.is_in_progress():
        # Get current date
        date = get_current_date(request.user, event)

        if date is None:
            # No next date, the event should be over
            matches = Pick.objects.get_all_matches_by_user_and_event(request.user, event)

            # Apply consolation credit
            consolation_credit = 0
            if len(matches) == 0:
                consolation_credit = Transaction.objects.apply_consolation_credit(request.user, event)

            context = {
                'user': request.user,
                'event': event,
                'matches': matches,
                'consolation_credit': float(consolation_credit) / 100
            }

            return render(request, 'chat/post_live.html', context)

        if date.is_break:
            context = {
                'event': event,
                'is_break': True,
                'time_passed': date.time_passed,
                'time_until_reload': date.time_until_reload,
                'next_date': date.next_date
            }

            return render(request, 'chat/live_break.html', context)

        if date.is_active:
            # Chat is in progress
            # Create a token
            opentok = OpenTok(api_key, api_secret)
            connection_metadata = 'username=' + request.user.username + ',eventId=' + str(event.id)
            token = opentok.generate_token(date.session_id, data=connection_metadata)

            # Mark conversation as token requested
            Conversation.objects.mark_token_requested(date.conversation_id)

            context = {
                'event': event,
                'is_break': False,
                'is_active': True,
                'user': date.user,
                'account': date.account,
                'memo': date.memo,
                'sessionID': date.session_id,
                'token': token,
                'tokbox_api_key': api_key,
                'time_passed': date.time_passed,
                'time_until_reload': date.time_until_reload
            }

            return render(request, 'chat/live.html', context)
        else:
            # Making a pick
            # Look up the previous pick result for the same pair and event
            pick_response = Pick.objects.get_response(request.user, date.user, event)

            context = {
                'event': event,
                'is_break': False,
                'is_active': False,
                'user': date.user,
                'account': date.account,
                'memo': date.memo,
                'time_passed': date.time_passed,
                'time_until_reload': date.time_until_reload,
                'pick_response': pick_response,
                'next_date': date.next_date
            }

            return render(request, 'chat/live_pick.html', context)

    if event.is_starting_soon():
        # Generate a new routed session and token
        opentok = OpenTok(api_key, api_secret)
        session = opentok.create_session(media_mode=MediaModes.routed)
        token = opentok.generate_token(session.session_id)

        dates = get_user_dates(request.user, event)

        context = {
            'event': event,
            'dates': dates,
            'time_until_reload': event.get_seconds_until_start(),
            'sessionID': session.session_id,
            'token': token,
            'tokbox_api_key': api_key
        }

        return render(request, 'chat/lobby.html', context)

    if event.is_ended_recently():
        matches = Pick.objects.get_all_matches_by_user_and_event(request.user, event)

        # Apply consolation credit
        consolation_credit = 0
        if len(matches) == 0:
            consolation_credit = Transaction.objects.apply_consolation_credit(request.user, event)

        context = {
            'user': request.user,
            'event': event,
            'matches': matches,
            'consolation_credit': float(consolation_credit) / 100
        }

        return render(request, 'chat/post_live.html', context)


def network_test(request):
    # Generate a new routed session and token
    opentok = OpenTok(api_key, api_secret)
    session = opentok.create_session(media_mode=MediaModes.routed)
    token = opentok.generate_token(session.session_id)

    context = {
        'sessionID': session.session_id,
        'token': token,
        'tokbox_api_key': api_key
    }

    return render(request, 'chat/network_test.html', context)


# # TODO: Temp method, delete later
# def live_event_test(request, user1, user2):
#     LOGGER.info('user ' + user1 + ' calls user ' + user2)
#     opentok = OpenTok(api_key, api_secret)
#
#     # Look up the session ID
#     key = '1' + '|' + str(user1) + '|' + str(user2)
#     session_id = cache.get(key)
#     if session_id is None:
#         key = '1' + '|' + str(user2) + '|' + str(user1)
#         session_id = cache.get(key)
#
#     # Create a session if it is missing
#     if session_id is None:
#         # Create a session that attempts to send streams directly between clients (falling back
#         # to use the OpenTok TURN server to relay streams if the clients cannot connect):
#         session = opentok.create_session()
#         # A session that uses the OpenTok Media Router, which is required for archiving
#         # session = opentok.create_session(media_mode=MediaModes.routed, archive_mode=ArchiveModes.always)
#         session_id = session.session_id
#         key = '1' + '|' + str(user1) + '|' + str(user2)
#         cache.set(key, session_id, 60 * 60 * 5)
#
#     # Create a token
#     connection_metadata = 'username=' + user1 + ',eventId=4'
#     token = opentok.generate_token(session_id, data=connection_metadata)
#     LOGGER.info('created token: ' + str(token))
#
#     context = {
#         'tokbox_api_key': api_key,
#         'sessionID': session_id or 'wait',
#         'token': token
#     }
#
#     return render(request, 'chat/test.html', context)


@login_required
def create_pick(request, target_user_id, event_id, response):
    pick = Pick.objects.pick_by_id(request.user, target_user_id, event_id, response)

    return JsonResponse({'picker': str(pick.picker), 'picked': str(pick.picked), 'event': str(pick.event),
                         'response': pick.response})

chat/templates/chat/live.html
{% extends 'web/base_chat.html' %}

{% load staticfiles %}
{% load account_tags %}

{% block title %}Bokaru | Live chat{% endblock %}

{% block header %}
<script src="https://static.opentok.com/v2/js/opentok.min.js"></script>
{% endblock %}

{% block content %}
<section>
    <div class="container g-height-600 g-pos-rel g-pa-0">
        <!-- Videos -->
        <div id="local_video" class="g-pos-abs" style="bottom: 5px; right: 5px; height: 150px; width: 200px; border: 1px solid #fff; z-index: 1000; background: rgba(0, 0, 0, 0.5);"></div>
        <div id="remote_video" class="g-height-600" style="background: rgba(0, 0, 0, 0.5);"></div>
        <!-- End Videos -->
        <div id="video_info" class="h1 g-pos-abs text-center" style="top: 45%; left: 0; z-index: 1; width: 100%;">
            Waiting for your date&hellip;
        </div>
        <div id="countdown" class="h1 g-pos-abs text-center g-color-primary g-font-size-180" style="top: 30%; left: 0; z-index: 1; width: 100%;">
        </div>
    </div>
</section>


<section>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <!-- Countdown -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="progress g-my-20">
                            <div id="timer" class="progress-bar progress-bar-striped progress-bar-animated"
                                 role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                </div>
                <!-- End Countdown -->
            </div>
        </div>
        <div class="row g-mb-150">
            <div class="col-12">
                {% render_profile_large account memo %}
            </div>
        </div>
    </div>
</section>
{% csrf_token %}
{% endblock %}

{% block javascript %}
<script>
var sessionId = '{{ sessionID }}'
var token = '{{ token }}'
var apiKey = '{{ tokbox_api_key }}'

$(document).on('ready', function () {
    let csrftoken = $('[name=csrfmiddlewaretoken]').val()

    var dateDuration = {{ event.dateDuration }}
    var timeUntilReload = {{ time_until_reload }}
    var seconds = 0
    let countdown = $('#countdown')
    let timer = $('#timer')

    function updateTimer() {
        let secondsElapsed = dateDuration - timeUntilReload + seconds++
        let progress = secondsElapsed / dateDuration * 100

        let secondsLeft = Math.round(timeUntilReload) - seconds
        let minutesLeft = (secondsLeft - secondsLeft % 60) / 60
        secondsLeft = secondsLeft - minutesLeft * 60

        let timeString = (minutesLeft+'').padStart(2,'0') + ':' + (secondsLeft+'').padStart(2,'0')

        timer.css("width", progress + '%')
        timer.html(timeString)

        document.title = 'Bokaru | ' + timeString

        if (minutesLeft === 0 && secondsLeft <= 10) {
            countdown.html(secondsLeft)
        }
    }

    setInterval(updateTimer, 1000)

    // Handle memo button clicks
    $('.save_memo_button').click(function() {
        user_id = $(this).data('user-id')
        let memo = $('.memo[data-user-id=' + user_id +']')
        let saving = $('.saving_memo[data-user-id=' + user_id +']')
        let text = memo.val()
        $.ajaxSetup({
            headers: {
                'X-CSRFToken': csrftoken
            }
        })
        saving.show()
        $.post('/memo/about/'+ user_id + '/', text, function() {
            saving.hide()
        })
    })
})
</script>
<script src="{% static 'chat/js/chat.js' %}"></script>

<script>
    gtag('event', 'chat_date', {
        'event_category': 'chat',
        'event_label': '{{ event.name }}'
    });
</script>
{% endblock %}

chat/templates/chat/live_break.html
{% extends 'web/base_chat.html' %}

{% load staticfiles %}
{% load account_tags %}

{% block title %}Bokaru | Live chat{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center g-my-50">
                <h1>Next date is coming up soon, hang on!</h1>
                <h3>There are fewer people in the other group, so we had to schedule a break between your dates.</h3>
                <p>But this could be a great opportunity to grab a nice cup of tea!</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="progress g-my-50">
                    <div id="timer" class="progress-bar progress-bar-striped progress-bar-animated"
                         role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
        </div>
        {% if next_date %}
        <div class="row g-mb-150">
            <div class="col-12">
                <h1>Coming up next:</h1>
                {% if next_date.is_break %}
                <h3>Another short break between dates, due to a different number of people in the groups.</h3>
                <p>Might as well make it 2 cups of tea!</p>
                {% else %}
                {% render_profile_large next_date.account next_date.memo %}
                {% endif %}
            </div>
        </div>
        {% else %}
        <div class="row g-mb-150">
            <div class="col-12">
                <h1>This was the last date</h1>
                <h2>The results will soon be revealed!</h2>
            </div>
        </div>
        {% endif %}
    </div>
</section>
{% csrf_token %}
{% endblock %}

{% block javascript %}
<script>
$(document).on('ready', function () {
    let csrftoken = $('[name=csrfmiddlewaretoken]').val()
    var dateDuration = {{ event.dateDuration }}
    var breakDuration = {{ event.breakDuration }}
    var timeUntilReload = {{ time_until_reload }}
    var seconds = 0

    function updateTimer() {
        let timer = $('#timer')
        let secondsElapsed = dateDuration + breakDuration - timeUntilReload + seconds++
        let progress = secondsElapsed / (dateDuration + breakDuration) * 100

        let secondsLeft = Math.round(timeUntilReload) - seconds
        let minutesLeft = (secondsLeft - secondsLeft % 60) / 60
        secondsLeft = secondsLeft - minutesLeft * 60

        let timeString = (minutesLeft+'').padStart(2,'0') + ':' + (secondsLeft+'').padStart(2,'0')

        document.title = 'Bokaru | ' + timeString

        timer.css("width", progress + '%')
        timer.html(timeString)
    }

    setInterval(updateTimer, 1000)

    // Handle memo button clicks
    $('.save_memo_button').click(function() {
        user_id = $(this).data('user-id')
        let memo = $('.memo[data-user-id=' + user_id +']')
        let saving = $('.saving_memo[data-user-id=' + user_id +']')
        let text = memo.val()
        $.ajaxSetup({
            headers: {
                'X-CSRFToken': csrftoken
            }
        })
        saving.show()
        $.post('/memo/about/'+ user_id + '/', text, function() {
            saving.hide()
        })
    })
})
</script>

<script>
    gtag('event', 'chat_break', {
        'event_category': 'chat',
        'event_label': '{{ event.name }}'
    });
</script>
{% endblock %}

chat/templates/chat/live_pick.html
{% extends 'web/base_chat.html' %}

{% load staticfiles %}
{% load account_tags %}

{% block title %}Bokaru | Live chat{% endblock %}

{% block content %}
<section>
    <div class="container g-bg-secondary">
        <!-- Pick buttons -->
        <div class="row">
            <div class="col-12 text-center g-my-50">
                <h1>Was it a match?</h1>
                <p>Your contact information will be shared with this user in the event that they select you as a match as well.</p>
            </div>
            <!-- Yay -->
            <div class="col-6">
                <div id="select_yes" class="u-shadow-v22 rounded-0 g-px-30 g-pb-30 g-mb-30 custom-radio text-center">
                    <span class="u-icon-v3 g-bg-secondary g-color-primary g-rounded-5 g-pull-50x-up g-mb-5">
                        <i class="fa fa-thumbs-o-up"></i>
                    </span>
                    <h3>YES</h3>
                    <h5>I'd like to talk more!</h5>
                </div>
            </div>

            <!-- Nay -->
            <div class="col-6">
                <div id="select_no" class="u-shadow-v22 rounded-0 g-px-30 g-pb-30 g-mb-30 custom-radio text-center">
                    <span class="u-icon-v3 g-bg-secondary g-color-primary g-rounded-5 g-pull-50x-up g-mb-5">
                        <i class="fa fa-thumbs-o-down"></i>
                    </span>
                    <h3>NO</h3>
                    <h5>I'm going to pass</h5>
                </div>
            </div>
        </div>
        <!-- End pick buttons -->
    </div>
</section>

<section>
    <div class="container">
        <div class="row g-bg-secondary">
            <div class="col-12">
                <!-- Countdown -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="progress g-mb-20">
                            <div id="timer" class="progress-bar progress-bar-striped progress-bar-animated"
                                 role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                </div>
                <!-- End Countdown -->
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <h1>You just talked to</h1>
                {% render_profile_large account memo %}
            </div>
        </div>
        {% if next_date %}
        <div class="row g-mb-150">
            <div class="col-12">
                <h1>Coming up next:</h1>
                {% if next_date.is_break %}
                <h2>A short break between dates.</h2>
                <p>There are fewer people in the other group, so we had to schedule a break between your dates.</p>
                {% else %}
                {% render_profile_large next_date.account next_date.memo %}
                {% endif %}
            </div>
        </div>
        {% else %}
        <div class="row g-mb-150">
            <div class="col-12">
                <h1>This was the last date</h1>
                <h2>The results will soon be revealed!</h2>
            </div>
        </div>
        {% endif %}
    </div>
</section>
{% csrf_token %}
{% endblock %}

{% block javascript %}
<script type="text/javascript">
$(document).on('ready', function () {
    let csrftoken = $('[name=csrfmiddlewaretoken]').val()

    var breakDuration = {{ event.breakDuration }}
    var timeUntilReload = {{ time_until_reload }}
    var seconds = 0

    function updateTimer() {
        let timer = $('#timer')
        let secondsElapsed = breakDuration - timeUntilReload + seconds++
        let progress = secondsElapsed / breakDuration * 100

        let secondsLeft = Math.round(timeUntilReload) - seconds
        let minutesLeft = (secondsLeft - secondsLeft % 60) / 60
        secondsLeft = secondsLeft - minutesLeft * 60

        let timeString = (minutesLeft+'').padStart(2,'0') + ':' + (secondsLeft+'').padStart(2,'0')

        document.title = 'Bokaru | ' + timeString

        timer.css("width", progress + '%')
        timer.html(timeString)
    }

    setInterval(updateTimer, 1000)

    // Handle memo button clicks
    $('.save_memo_button').click(function() {
        user_id = $(this).data('user-id')
        let memo = $('.memo[data-user-id=' + user_id +']')
        let saving = $('.saving_memo[data-user-id=' + user_id +']')
        let text = memo.val()
        $.ajaxSetup({
            headers: {
                'X-CSRFToken': csrftoken
            }
        })
        saving.show()
        $.post('/memo/about/'+ user_id + '/', text, function() {
            saving.hide()
        })
    })

    // Handle pick buttons
    let selectYes = $('#select_yes')
    let selectNo = $('#select_no')

    selectYes.click(function() {
        selectYes.removeClass('custom-radio')
        selectYes.addClass('custom-radio-active')

        selectNo.removeClass('custom-radio-active')
        selectNo.addClass('custom-radio')

        submitAnswer(1)
    })

    selectNo.click(function() {
        selectNo.removeClass('custom-radio')
        selectNo.addClass('custom-radio-active')

        selectYes.removeClass('custom-radio-active')
        selectYes.addClass('custom-radio')

        submitAnswer(0)
    })

    function handleAjaxError(jqXHR, textStatus, errorThrown) {
        alert('We failed to save your choice, please refresh the page and try again!')
    }

    function submitAnswer(answer) {
        var eventID = '{{event.id}}'
        var pickID = '{{user.id}}'
        $.ajaxSetup({
            headers: {
                'X-CSRFToken': csrftoken
            },
            error: handleAjaxError
        })
	    var url = '/chat/pick/target_user/' + pickID + '/event/' + eventID + '/response/' + answer + '/'

        $.post(url)
	}

	// Show the previously selected pick response
	pick_response = {{ pick_response }}

	if (pick_response === 1) {
        selectYes.removeClass('custom-radio')
        selectYes.addClass('custom-radio-active')
	} else if (pick_response === 0) {
	    selectNo.removeClass('custom-radio')
        selectNo.addClass('custom-radio-active')
	}
})
</script>

<script>
    gtag('event', 'chat_pick', {
        'event_category': 'chat',
        'event_label': '{{ event.name }}'
    });
</script>
{% endblock %}

chat/templates/chat/network_test.html
{% extends 'web/base_nav.html' %}

{% load staticfiles %}

{% block title %}Bokaru | Network Test{% endblock %}

{% block header %}
<script src="https://static.opentok.com/v2/js/opentok.min.js"></script>
{% endblock %}

{% block content %}

<section class="g-mb-100">
    <div class="container text-center">
        <div class="row g-py-200--md g-py-80 g-min-height-50vh">
            <div class="col-md-8 ml-md-auto mr-md-auto">
                <div class="u-heading-v7-2 g-mb-30">
                    <h2 class="g-color-black g-font-weight-700 g-font-size-50 g-line-height-1 g-mb-20">Network Test</h2>
                    <span class="u-icon-v1 g-mr-15 g-mb-15">
                        <i class="fa fa-video-camera g-color-primary"></i>
                    </span>
                    <span class="u-icon-v1 g-mr-15 g-mb-15">
                        <i class="fa fa-headphones g-color-primary"></i>
                    </span>
                    <span class="u-icon-v1 g-mr-15 g-mb-15">
                        <i class="fa fa-signal g-color-primary"></i>
                    </span>
                    <span class="u-icon-v1 g-mr-15 g-mb-15">
                        <i class="fa fa-cogs g-color-primary"></i>
                    </span>
                    <span class="u-icon-v1 g-mr-15 g-mb-15">
                        <i class="fa fa-tachometer g-color-primary"></i>
                    </span>
                </div>

                <p id="welcome_text" class="lead g-mb-60">
                    Let's make sure that your computer, browser and internet connection are all up to the task of connecting you to all your dates!
                </p>

                <button id="start_button" class="btn btn-xl u-btn-primary rounded-0">
                    <i class="fa fa-video-camera g-mr-15"></i>
                    Start test
                </button>

                <div id="status_container" style="display:none;">
                    <h3>Testing stream capabilities</h3>
                    <p class="lead g-mb-60">Acquiring camera</p>
                    <span id="spinner" class="u-icon-v1 u-icon-size--lg">
                        <i class="fa fa-spinner spin g-color-primary"></i>
                    </span>
                    <span id="result_ok" class="u-icon-v1 u-icon-size--lg" style="display:none;">
                        <i class="fa fa-check-square-o g-color-primary"></i>
                    </span>
                    <span id="result_error" class="u-icon-v1 u-icon-size--lg" style="display:none;">
                        <i class="fa fa-times-circle g-color-primary"></i>
                    </span>
                    <span id="result_warning" class="u-icon-v1 u-icon-size--lg" style="display:none;">
                        <i class="fa fa-exclamation-triangle g-color-primary"></i>
                    </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 ml-md-auto mr-md-auto">
                <p>Having trouble? Please take a look at the <a href="{% url 'web:browser_support' %}">list of supported browsers</a>
                    or <a href="{% url 'web:contact_us' %}">contact us</a> for support.</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>
var API_KEY = '{{ tokbox_api_key }}';
var SESSION_ID = '{{ sessionID }}';
var TOKEN = '{{ token }}';
</script>
<script src="{% static 'chat/js/network_test.js' %}"></script>

<script>
    gtag('event', 'chat_test', {
        'event_category': 'chat',
        'event_label': '{{ event.name }}'
    });
</script>
{% endblock %}

chat/templates/chat/no_live.html
{% extends 'web/base_nav.html' %}

{% load staticfiles %}
{% load event_tags %}

{% block title %}Bokaru | Live chat{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row g-min-height-50vh">
            <div class="col-md-12 g-mt-50--md" style="text-align: center;">
                <h1>No events starting soon</h1>
                {% if next_event %}
                <h2>Next event is coming up in {{ next_event.startDateTime|timeuntil }}</h2>
                <div class="g-my-50">
                    <!-- Event -->
                    {% render_event_large next_event %}
                    <!-- End Event -->
                </div>
                {% else %}
                <div class="heading margin-bottom-40">
                    <h2>You have not signed up for any events yet</h2>
                    <br/>
                    <h2><a href="{% url 'web:search' %}">Find one now!</a></h2>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>
    gtag('event', 'chat_none', {
        'event_category': 'chat'
    });
</script>
{% endblock %}

chat/templates/chat/post_live.html
{% extends 'web/base_nav.html' %}

{% load staticfiles %}
{% load account_tags %}

{% block title %}Bokaru | Live chat{% endblock %}

{% block content %}
<section>
    <div class="container g-min-height-50vh">
        <div class="row text-center g-my-50">
            <div class="col-12">
                {% if matches|length > 0 %}
                <h1>TADA!</h1>
                <h3>The event is over now. Check out your matches below!</h3>
                {% else %}
                <h1>Whoops!</h1>
                <h3>You didn't match with anyone in this event.</h3>
                {% if consolation_credit > 0 %}
                <h4 class="h1 g-mt-25">On the positive side, here's a credit for <span class="g-color-primary">CAD ${{consolation_credit|floatformat:"2"}}</span> to try again!</h4>
                {% endif %}
                {% endif %}
                <h3 class="g-my-100">Please take a minute to fill out our
                <a href="https://docs.google.com/forms/d/e/1FAIpQLSf-88TyVnrEIC-KjJHRALxUaG44EZXGG8R7qfVyKzDAIqgC5g/viewform?usp=pp_url&entry.1423063305={{user.username}}&entry.919213445={{event.id}}&entry.349499540&entry.543626436&entry.280677627"
                   target="_blank" class="btn btn-lg u-btn-primary rounded-0">Questionnaire</a>
                </h3>
            </div>
        </div>
        <div class="row g-my-50">
            {% for match in matches %}
            <div class="col-sm-6">
                {% render_profile_medium_by_user match %}
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}



{% block javascript %}
<script>
    gtag('event', 'chat_done', {
        'event_category': 'chat',
        'event_label': '{{ event.name }}'
    });
</script>
{% endblock %}