account/urls.py
from django.urls import path, include

from . import views, views_registration

app_name = 'account'
urlpatterns = [
    path('profile/', include([
        path('', views.view, name='view'),
        path('view/<str:username>/', views.view_user, name='view_user'),
        path('edit/', views.edit, name='edit')
    ])),
    path('account/', include([
        path('', views.preferences, name='preferences'),
        path('payment/', views.preferences_payment, name='payment'),
        path('payment_history/', views.preferences_payment_history, name='payment_history'),
        path('close/', views.close, name='close')
    ])),
    # Registration views
    path('register/', include([
        path('', views_registration.register, name='register'),
        path('join/<int:group_id>', views_registration.register_and_join_group, name='register_and_join'),
        path('done/', views_registration.register_success, name='registration_success'),
        path('activate/<str:activation_key>', views_registration.activate, name='registration_activate'),
    ])),

    # Usage example: $.post( "/memo/about/2/", "lorem ipsum dolor sit amet");
    path('memo/about/<str:about_user_id>/', views.create_or_update_memo, name='memo')
]

bokaru/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = \
    [
        path('', include('web.urls')),
        path('', include('account.urls')),
        path('event/', include('event.urls')),
        path('chat/', include('chat.urls')),
        path('admin/', admin.site.urls),
        path('script/activate_events/', views.activate_events),
        path('script/process_payments/', views.process_payments),
        # Authentication views
        path('', include('django.contrib.auth.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

web/urls.py
from django.urls import path

from . import views

app_name = 'web'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('search/<str:place_name>/', views.search_by_place, name='search_by_place'),
    path('my_events/', views.my_events, name='my_events'),
    path('my_matches/', views.my_matches, name='my_matches'),
    # ============
    # Static pages
    # ============
    path('about_us/', views.about_us, name='about_us'),
    path('browser_support/', views.browser_support, name='browser_support'),
    path('community_guidelines/', views.community_guidelines, name='community_guidelines'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('how_it_works/', views.how_it_works, name='how_it_works'),
    path('pricing/', views.pricing, name='pricing'),
    path('privacy_statement/', views.privacy_statement, name='privacy_statement'),
    path('refund_policy/', views.refund_policy, name='refund_policy'),
    path('safety_tips/', views.safety_tips, name='safety_tips'),
    path('terms_of_service/', views.terms_of_service, name='terms_of_service')
]

web/templates/web/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">

<head>
    <!-- Title -->
    <title>{% block title %}Bokaru{% endblock %}</title>

    <!-- Required Meta Tags Always Come First -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="theme-color" content="#e74c3c"/>

    <!-- Favicon -->
    <link rel="shortcut icon" href="favicon.ico">

    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans%3A400%2C300%2C500%2C600%2C700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Comfortaa">

    <!-- CSS Compulsory -->
    <link rel="stylesheet" href="{% static 'web/vendor/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/vendor/bootstrap/offcanvas.css' %}">

    <!-- CSS Icons -->
    <link rel="stylesheet" href="{% static 'web/vendor/icon-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/vendor/icon-line/css/simple-line-icons.css' %}">
    <link rel="stylesheet" href="{% static 'web/vendor/hamburgers/hamburgers.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/vendor/icon-hs/style.css' %}">

    <!-- CSS Plugins -->
    <link rel="stylesheet" href="{% static 'web/vendor/animate.css' %}">
    <link rel="stylesheet" href="{% static 'web/vendor/dzsparallaxer/dzsparallaxer.css' %}">
    <link rel="stylesheet" href="{% static 'web/vendor/dzsparallaxer/dzsscroller/scroller.css' %}">
    <link rel="stylesheet" href="{% static 'web/vendor/dzsparallaxer/advancedscroller/plugin.css' %}">
    <link rel="stylesheet" href="{% static 'web/vendor/hs-megamenu/src/hs.megamenu.css' %}">
    <link rel="stylesheet" href="{% static 'web/vendor/cropper/cropper.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/vendor/jquery-ui/themes/base/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/vendor/custombox/custombox.min.css' %}">

    <!-- CSS Unify -->
    <link rel="stylesheet" href="{% static 'web/css/unify-core.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/unify-components.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/unify-globals.min.css' %}">

    <!-- CSS Customization -->
    <link rel="stylesheet" href="{% static 'web/css/custom.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/bokaru.css' %}">

    <!-- Google Analytics -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-110522977-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-110522977-1');
    </script>

    {% block header %}
    {% endblock %}
</head>

<body>
{% block main %}
{% endblock %}


<!-- JS Global Compulsory -->
<script src="{% static 'web/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'web/vendor/jquery-migrate/jquery-migrate.min.js' %}"></script>
<script src="{% static 'web/vendor/jquery.easing/js/jquery.easing.js' %}"></script>
<script src="{% static 'web/vendor/popper.min.js' %}"></script>
<script src="{% static 'web/vendor/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'web/vendor/bootstrap/offcanvas.js' %}"></script>

<!-- JS Implementing Plugins -->
<script src="{% static 'web/vendor/hs-megamenu/src/hs.megamenu.js' %}"></script>
<script src="{% static 'web/vendor/appear.js' %}"></script>
<script src="{% static 'web/vendor/dzsparallaxer/dzsparallaxer.js' %}"></script>
<script src="{% static 'web/vendor/dzsparallaxer/dzsscroller/scroller.js' %}"></script>
<script src="{% static 'web/vendor/dzsparallaxer/advancedscroller/plugin.js' %}"></script>
<script src="{% static 'web/vendor/cropper/cropper.min.js' %}"></script>
<script src="{% static 'web/vendor/custombox/custombox.min.js' %}"></script>
<script src="{% static 'web/vendor/jquery.countdown.min.js' %}"></script>
<script src="{% static 'web/vendor/circles/circles.min.js'%}"></script>

<!-- JS Unify -->
<script src="{% static 'web/js/hs.core.js' %}"></script>

<script src="{% static 'web/js/components/hs.header.js' %}"></script>
<script src="{% static 'web/js/components/hs.scrollbar.js' %}"></script>
<script src="{% static 'web/js/components/hs.popup.js' %}"></script>
<script src="{% static 'web/js/components/hs.go-to.js' %}"></script>
<script src="{% static 'web/js/components/hs.dropdown.js' %}"></script>
<script src="{% static 'web/js/components/hs.onscroll-animation.js' %}"></script>
<script src="{% static 'web/js/components/hs.counter.js' %}"></script>
<script src="{% static 'web/js/components/hs.modal-window.js' %}"></script>
<script src="{% static 'web/js/helpers/hs.not-empty-state.js' %}"></script>
<script src="{% static 'web/js/components/hs.countdown.js' %}"></script>
<script src="{% static 'web/js/components/hs.chart-pie.js'%}"></script>

<!-- jQuery UI Helpers -->
<script src="{% static 'web/js/helpers/hs.hamburgers.js' %}"></script>
<script src="{% static 'web/js/helpers/hs.focus-state.js' %}"></script>
<script src="{% static 'web/js/helpers/hs.height-calc.js' %}"></script>

<!-- JS Custom -->
<script src="{% static 'web/js/custom.js' %}"></script>

<!-- Stripe -->
<script src="https://js.stripe.com/v3/"></script>

<!-- JS Plugins Init. -->
<script>
$(document).on('ready', function () {
    // initialization of go to
    $.HSCore.components.HSGoTo.init('.js-go-to')

    // initialization of forms
    $.HSCore.helpers.HSFocusState.init();
    $.HSCore.helpers.HSNotEmptyState.init()

    // initialization of HSScrollBar component
    $.HSCore.components.HSScrollBar.init($('.js-scrollbar'))

    // initialization of scroll animation
    $.HSCore.components.HSOnScrollAnimation.init('[data-animation]')

    // initialization of HSDropdown component
    $.HSCore.components.HSDropdown.init($('[data-dropdown-target]'))

    // initialization of counters
    var counters = $.HSCore.components.HSCounter.init('[class*="js-counter"]')

    // initialization of popups
    $.HSCore.components.HSModalWindow.init('[data-modal-target]')

    // initialization of countdowns
    var countdowns = $.HSCore.components.HSCountdown.init('.js-countdown', {
        yearsElSelector: '.js-cd-years',
        monthElSelector: '.js-cd-month',
        daysElSelector: '.js-cd-days',
        hoursElSelector: '.js-cd-hours',
        minutesElSelector: '.js-cd-minutes',
        secondsElSelector: '.js-cd-seconds'
    })

    // initialization of chart pies
    let items = $.HSCore.components.HSChartPie.init('.js-pie')

    // initialization of tooltips
    $('[data-toggle="tooltip"]').tooltip()
})

$(window).on('load', function () {
    // initialization of header
    $.HSCore.components.HSHeader.init($('#js-header'))
    $.HSCore.helpers.HSHamburgers.init('.hamburger')
    // initialization of HSMegaMenu component
    $('.js-mega-menu').HSMegaMenu({
        event: 'hover',
        pageContainer: $('.container'),
        breakpoint: 991
    })
})
</script>

{% block javascript %}
{% endblock %}

</body>
</html>

web/templates/web/how_it_works.html
{% extends 'web/base_nav.html' %}

{% load staticfiles %}

{% block content %}

<section class="g-min-height-50vh">
    <div class="container g-py-50 g-py-150--md">
        <div class="row g-mb-50">
            <div class="col-lg-6">
                <div class="d-inline-block g-width-80 g-height-4 g-bg-black mb-3"></div>
                <h2 class="g-color-black g-font-weight-700 g-font-size-50 g-line-height-1 mb-4">How It Works</h2>
            </div>
        </div>

        <div class="row justify-content-center g-mb-60">
            <div class="col-lg-7">
                <div class="text-center mb-4">
                    <h2 class="h3 text-uppercase mb-3">Our services</h2>
                    <div class="d-inline-block g-width-60 g-height-1 g-bg-black mb-2"></div>
                    <p class="lead mb-0">
                        We offer live video datings that run just like speed dating except from the comfort of home.
                        You'll meet up to 15 singles on a set of 5 minute dates and you can see who is attending before you even sign up.
                        Once the event is done you'll get your matches immediately so you can get the sparks flying!
                    </p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4 g-mb-30">
                <div class="g-brd-around--md g-brd-gray-light-v4 text-center g-pa-10 g-px-30--lg g-py-40--lg">
                    <span class="d-block g-color-gray-dark-v4 g-font-size-40 g-mb-15">
                        <span class="u-icon-v2 g-rounded-5 g-mb-25">
                            <i class="icon-magnifier"></i>
                        </span>
                    </span>
                    <h3 class="g-color-black g-mb-10">Find the Right Event For You</h3>
                    <p class="g-color-gray-dark-v4">Whether it be dog lovers, cat walkers, sky divers, or cave dwellers find the right event and meet the singles you’ll like.</p>
                    <div class="d-inline-block g-width-40 g-brd-bottom g-brd-gray-dark-v5 g-my-15"></div>
                    <ul class="list-unstyled g-px-30 g-mb-0">
                        <li class="g-brd-bottom g-brd-gray-light-v3 g-py-10">Themed events to match your interests</li>
                        <li class="g-brd-bottom g-brd-gray-light-v3 g-py-10">Event sizes to match your busy schedule.</li>
                        <li class="g-brd-bottom g-brd-gray-light-v3 g-py-10">View participants before you join.</li>
                        <li class="g-py-10">Can't find an event? Create your own</li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4 g-mb-30">
                <div class="g-brd-around--md g-brd-gray-light-v4 text-center g-pa-10 g-px-30--lg g-py-40--lg">
                    <span class="d-block g-color-gray-dark-v4 g-font-size-40 g-mb-15">
                        <span class="u-icon-v2 g-rounded-5 g-mb-25">
                            <i class="icon-user"></i>
                        </span>
                    </span>
                    <h3 class="g-color-black g-mb-10">Read Profiles</h3>
                    <p class="g-color-gray-dark-v4">Don't waste time asking your date basic questions, read their profile upfront then get to the important questions faster!</p>
                    <div class="d-inline-block g-width-40 g-brd-bottom g-brd-gray-dark-v5 g-my-15"></div>
                    <ul class="list-unstyled g-px-30 g-mb-0">
                        <li class="g-brd-bottom g-brd-gray-light-v3 g-py-10">Get the basics out of the way</li>
                        <li class="g-brd-bottom g-brd-gray-light-v3 g-py-10">Learn about their lifestyle choices</li>
                        <li class="g-brd-bottom g-brd-gray-light-v3 g-py-10">Find out what they are looking for.</li>
                        <li class="g-py-10">See their profile picture before you meet</li>

                    </ul>
                </div>
            </div>
            <div class="col-md-4 g-mb-30">
                <div class="g-brd-around--md g-brd-gray-light-v4 text-center g-pa-10 g-px-30--lg g-py-40--lg">
                    <span class="d-block g-color-gray-dark-v4 g-font-size-40 g-mb-15">
                        <span class="u-icon-v2 g-rounded-5 g-mb-25">
                            <i class="icon-camera"></i>
                        </span>
                    </span>
                    <h3 class="g-color-black g-mb-10">Live Video Dates</h3>
                    <p class="g-color-gray-dark-v4">No messaging only dating. Have up to 15 live video dates today.</p>
                    <div class="d-inline-block g-width-40 g-brd-bottom g-brd-gray-dark-v5 g-my-15"></div>
                    <ul class="list-unstyled g-px-30 g-mb-0">
                        <li class="g-brd-bottom g-brd-gray-light-v3 g-py-10">Actually meet to real people live</li>
                        <li class="g-brd-bottom g-brd-gray-light-v3 g-py-10">No downloads required</li>
                        <li class="g-py-10">View your date lineup before you begin</li>

                    </ul>
                </div>
            </div>

            <div class="col-md-4 g-mb-30">
                <div class="g-brd-around--md g-brd-gray-light-v4 text-center g-pa-10 g-px-30--lg g-py-40--lg">
                    <span class="d-block g-color-gray-dark-v4 g-font-size-40 g-mb-15">
                        <span class="u-icon-v2 g-rounded-5 g-mb-25">
                            <i class="icon-note"></i>
                        </span>
                    </span>
                    <h3 class="g-color-black g-mb-10">Take Notes</h3>
                    <p class="g-color-gray-dark-v4">The best part of meeting so many people is trying to remember who is who so take notes as you go to remember those special someones.</p>
                    <div class="d-inline-block g-width-40 g-brd-bottom g-brd-gray-dark-v5 g-my-15"></div>
                    <ul class="list-unstyled g-px-30 g-mb-0">
                        <li class="g-brd-bottom g-brd-gray-light-v3 g-py-10">Take notes based on what you see on their profile</li>
                        <li class="g-brd-bottom g-brd-gray-light-v3 g-py-10">Refer to notes during dates</li>
                        <li class="g-py-10">Write down what you think so you can remember your date later.</li>
                    </ul>
                </div>
            </div>

            <div class="col-md-4 g-mb-30">
                <div class="g-brd-around--md g-brd-gray-light-v4 text-center g-pa-10 g-px-30--lg g-py-40--lg">
                    <span class="d-block g-color-gray-dark-v4 g-font-size-40 g-mb-15">
                        <span class="u-icon-v2 g-rounded-5 g-mb-25">
                            <i class="icon-heart"></i>
                        </span>
                    </span>
                    <h3 class="g-color-black g-mb-10">Instant Matches</h3>
                    <p class="g-color-gray-dark-v4">Don’t wait a week to find out if that special lady or gentleman likes you back; once you click, start clicking.</p>
                    <div class="d-inline-block g-width-40 g-brd-bottom g-brd-gray-dark-v5 g-my-15"></div>
                    <ul class="list-unstyled g-px-30 g-mb-0">
                        <li class="g-brd-bottom g-brd-gray-light-v3 g-py-10">You'll see who liked you back at the end of the event.</li>
                        <li class="g-brd-bottom g-brd-gray-light-v3 g-py-10">You can start talking IRL while you still remember who they are.</li>
                        <li class="g-py-10">See who your past matches are from previous events.</li>
                    </ul>
                </div>
            </div>

            <div class="col-md-4 g-mb-30 g-color-primary">
                <div class="g-brd-around--md g-brd-gray-light-v4 text-center g-pa-10 g-px-30--lg g-py-40--lg">
                    <span class="d-block g-color-primary g-font-size-40 g-mb-15">
                        <span class="u-icon-v2 g-rounded-5 g-mb-25">
                            <i class="icon-direction"></i>
                        </span>
                    </span>
                    <h3 class="g-mb-10 ">Start Now</h3>
                    <p class="">Why are you still here?</p>
                    <div class="d-inline-block g-width-40 g-brd-bottom g-brd-gray-dark-v5 g-my-15"></div>
                    <ul class="list-unstyled g-px-30 g-mb-0">
                        <li class="nav-item g-mx-20--lg">
                            <a href="{% url 'web:search' %}" class="btn btn-lg u-btn-primary g-mb-10 rounded-0">Find Events</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

web/templates/web/index.html
{% extends 'web/base_nav.html' %}

{% load staticfiles %}
{% load event_tags %}
{% load account_tags %}

{% block nav_location %}nav_home{% endblock %}

{% block content %}
<section class="g-mb-100">
    <div class="container">
        <div class="row g-min-height-50vh">
            <div class="col-lg-4">
                <!-- User Image -->
                <div class="g-mb-20">
                    <div class="u-shadow-v2 g-brd-around g-brd-gray-light-v4 g-line-height-2">
                        {% if account.photo is None or account.photo.name == '' %}
                        <img class="img-fluid w-100" src="{% static 'web/images/user_default_image.jpg' %}"
                             alt="Default picture" id="default_avatar"/>
                        {% else %}
                        <img class="img-fluid w-100" src="{{ account.photo.url }}" alt="Profile picture"
                             id="avatar"/>
                        {% endif %}
                    </div>

                    <div class="list-group list-group-border-0 g-mb-40">
                        <a href="{% url 'account:view' %}" class="list-group-item list-group-item-action justify-content-between">
                            <span><i class="icon-user g-pos-rel g-top-1 g-mr-8"></i> My Profile</span>
                        </a>
                        <a href="{% url 'account:preferences' %}" class="list-group-item list-group-item-action justify-content-between">
                            <span><i class="icon-settings g-pos-rel g-top-1 g-mr-8"></i> My Account</span>
                        </a>
                        {% if remaining_credit > 0 %}
                        <div class="list-group-item list-group-item-action justify-content-between">
                            <span><i class="icon-present g-pos-rel g-top-1 g-mr-8"></i> Remaining site credit: CAD ${{ remaining_credit|floatformat:"2" }}</span>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-lg-8 g-mt-50--md">
                <h1>Upcoming Events</h1>
                {% if future_events|length == 0 %}
                <h3>Nothing here yet. Why not register for something?</h3>
                <a href="{% url 'web:search' %}" class="btn btn-lg btn-block u-btn-black g-my-20 rounded-0">
                    Search events
                </a>

                {% else %}

                {% for event in future_events %}
                <!-- Event -->
                <div class="g-mb-15">
                    {% render_event_large event %}
                </div>
                <!-- End Event -->
                {% endfor %}
                {% endif %}

                <hr/>

                <h1>Latest matches</h1>
                {% if latest_matches|length == 0 %}
                <h3>Nothing here yet, let's keep trying!</h3>
                <a href="{% url 'web:search' %}" class="btn btn-lg btn-block u-btn-black g-my-20 rounded-0">
                    Search events
                </a>
                {% else %}
                {% for match in latest_matches %}
                {% render_profile_medium_by_user match %}
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>
    gtag('event', 'visit_home', {
        'event_category': 'engagement',
    });
</script>
{% endblock %}

web/templates/web/login.html
<!DOCTYPE html>

{% load static %}

<!--[if IE 8]><html lang="en" class="ie8"><![endif]-->
<!--[if IE 9]><html lang="en" class="ie9"><![endif]-->
<!--[if !IE]><!-->
<html lang="en"> <!--<![endif]-->
<head>
    <title>Login 2 | Unify - Responsive Website Template</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Favicon -->
    <link rel="shortcut icon" href="favicon.ico">

    <!-- Web Fonts -->
    <link rel="stylesheet" type="text/css"
          href="//fonts.googleapis.com/css?family=Open+Sans:400,300,700&amp;subset=cyrillic,latin">

    <!-- CSS Global Compulsory -->
    <link rel="stylesheet" href="{% static 'web/theme/plugins/bootstrap/css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'web/theme/css/style.css' %}">


    <!-- CSS Implementing Plugins -->
    <link rel="stylesheet" href="{% static 'web/theme/plugins/animate.css' %}">

    <link rel="stylesheet" href="{% static 'web/theme/plugins/line-icons/line-icons.css' %}">

    <link rel="stylesheet" href="{% static 'web/theme/plugins/font-awesome/css/font-awesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'web/theme/plugins/brand-buttons/brand-buttons.css' %}">


    <!-- CSS Page Style -->
    <link rel="stylesheet" href="{% static 'web/theme/css/pages/page_log_reg_v4.css' %}">


    <!-- CSS Theme -->
    <link rel="stylesheet" href="{% static 'web/theme/css/theme-colors/red.css' %}">


    <!-- CSS Customization -->
    <link rel="stylesheet" href="{% static 'web/theme/css/custom.css' %}">

</head>

<body>
<!--=== Content Part ===-->
<div class="container-fluid">
    <div class="row equal-height-columns">
        <div class="col-md-6 col-sm-6 hidden-xs image-block equal-height-column"></div>

        <div class="col-md-6 col-sm-6 form-block equal-height-column">
            <a href="{% url 'web:index' %}">
                <img src="{% static 'web/theme/img/bokaru-logo.png' %}" alt="">

            </a>
            <h2 class="margin-bottom-30">Login To Your Account</h2>

            {% if form.errors %}
            <ul>
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                    {% endfor %}
                {% endfor %}
            </ul>
            {% endif %}

            <form action="{% url 'web:login' %}" method="post">
                {% csrf_token %}
                <div class="login-block">
                    <div class="input-group margin-bottom-20">
                        <span class="input-group-addon rounded-left"><i class="icon-user color-red"></i></span>
                        <!--<input type="text" class="form-control rounded-right" placeholder="Username">-->
                        <span class="form-control rounded-right">{{ form.username }}</span>
                    </div>

                    <div class="input-group margin-bottom-20">
                        <span class="input-group-addon rounded-left"><i class="icon-lock color-red"></i></span>
                        <!--<input type="password" class="form-control rounded-right" placeholder="Password">-->
                        <span class="form-control rounded-right">{{ form.password }}</span>
                    </div>
                    <input type="hidden" name="next" value="{{ next }}"/>

                    <div class="checkbox">
                        <ul class="list-inline">
                            <li>
                                <label>
                                    <input type="checkbox"> Remember me
                                </label>
                            </li>

                            <li class="pull-right">
                                <a href="{% url 'web:password_reset' %}">Forgot password?</a>
                            </li>
                        </ul>
                    </div>

                    <div class="row margin-bottom-70">
                        <div class="col-md-12">
                            <button type="submit" class="btn-u btn-u-red btn-block rounded">Sign In</button>
                        </div>
                    </div>


                </div>
            </form>
        </div>
    </div>
</div><!--/container-->
<!--=== End Content Part ===-->

<!--=== Sticky Footer ===-->
<div class="container sticky-footer">
    <ul class="list-unstyled list-inline social-links margin-bottom-20">
        <li><a href="#"><i class="icon-custom icon rounded-x icon-bg-red fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="icon-custom icon rounded-x icon-bg-red fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="icon-custom icon rounded-x icon-bg-red fa fa-google-plus"></i></a></li>
    </ul>
    <p class="copyright-space">
        2016 &copy; All Rights Reserved. Bokaru Inc.
    </p>
</div>
<!--=== End Sticky Footer ===-->

<!-- JS Global Compulsory -->
<script src="{% static 'web/theme/plugins/jquery/jquery.min.js' %}"></script>

<script src="{% static 'web/theme/plugins/jquery/jquery-migrate.min.js' %}"></script>

<script src="{% static 'web/theme/plugins/bootstrap/js/bootstrap.min.js' %}"></script>


<!-- JS Implementing Plugins -->
<script src="{% static 'web/theme/plugins/back-to-top.js' %}"></script>


<script src="{% static 'web/theme/plugins/backstretch/jquery.backstretch.min.js' %}"></script>


<!-- JS Customization -->
<script src="{% static 'web/theme/js/custom.js' %}"></script>


<!-- JS Page Level -->
<script src="{% static 'web/theme/js/app.js' %}"></script>

<script>
		jQuery(document).ready(function() {
			App.init();
		});


</script>
<script>
		$(".image-block").backstretch([
			"{% static 'web/theme/img/patterns/5.png' %}",
			"{% static 'web/theme/img/patterns/5.png' %}",

			], {
				fade: 1000,
				duration: 7000
			});


</script>
<!--[if lt IE 9]>
<script src="{% static 'web/theme/plugins/respond.js' %}"></script>

<script src="{% static 'web/theme/plugins/html5shiv.js' %}"></script>

<script src="{% static 'web/theme/plugins/placeholder-IE-fixes.js' %}"></script>

<![endif]-->
</body>
</html>